WebApplication2/WebApplication2/Models/ErrorViewModel.cs
using System;

namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication2/WebApplication2/Models/IPodMaths.cs
namespace WebApplication2.Models
{
    public interface IPodMaths
    {
        InterfaceM tec { get; set; }
        InterfaceM Nov();
    }
}

WebApplication2/WebApplication2/Models/InterfaceM.cs
namespace WebApplication2.Models
{
    public interface InterfaceM
    {
        int x { get; set; }
        int y { get; set; }

        int Add();
        int Sub();
        int Mult();
        int Div();
    }
}

WebApplication2/WebApplication2/Models/Maths.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Maths: InterfaceM
    {

        public int x { get; set; }
        public int y { get; set; }

        public Maths()
        {
            Random ran = new Random();
            x = ran.Next(0, 10);
            y = ran.Next(0, 10);
        }

        public int Add() { return x + y; }
        public int Sub() { return x - y; }
        public int Mult() { return x * y; }

        public int Div()
        {
            if (y == 0) { return 0; }
            else { return x / y; }
        }
    }

}

WebApplication2/WebApplication2/Models/PodMaths.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class PodMaths: IPodMaths
    {
        public InterfaceM tec { get; set; }
        public InterfaceM Nov()
        { tec = new Maths(); return tec; }
    }
}

WebApplication2/WebApplication2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication2/WebApplication2/Controllers/MathsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class MathsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PassUsingModel() //передает данные в представление
        {
            var ViewModel = new Maths();
            return View(ViewModel);//передача в представление "PassUsingModel"
        }

        public IActionResult PassUsingViewData()
        {
            ViewData["Class"] = new Maths();
            return View();
        }

        public IActionResult PassUsingViewBag()
        {
            ViewBag.Class = new Maths();
            return View();
        }

        public IActionResult AccessServiceDirectly()
        {
            ViewData["Title"] = "AccessServiceDirectly";
            return View();
        }

    }
}

WebApplication2/WebApplication2/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebApplication2/WebApplication2/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication2/WebApplication2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div style=" text-align:left">
    <h2>Calc Service Demonstration</h2>
    <ul>
        <li> <a asp-controller="Maths" asp-action="PassUsingModel">Using Model Calc</a></li>
        <li> <a asp-controller="Maths" asp-action="PassUsingViewData">Using ViewData Calc</a></li>
        <li> <a asp-controller="Maths" asp-action="PassUsingViewBag">Using ViewBag Calc</a></li>
        <li> <a asp-controller="Maths" asp-action="AccessServiceDirectly">Using Service Injection Calc</a></li>
    </ul>
</div>

WebApplication2/WebApplication2/Views/Maths/AccessServiceDirectly.cshtml
@{
    @inject IPodMaths PodMaths;
    @PodMaths.Nov();
 }

<h2>@ViewData["Title"]</h2>
<h5><b>Rand Value First :</b> @PodMaths.tec.x</h5>
<h5><b>Rand Value Second :</b> @PodMaths.tec.y</h5>
<h5><b>Add :</b><br>@PodMaths.tec.x + @PodMaths.tec.y = @PodMaths.tec.Add()</h5>
<h5><b>Sub :</b><br>@PodMaths.tec.x - @PodMaths.tec.y = @PodMaths.tec.Sub()</h5>
<h5><b>Mult :</b><br>@PodMaths.tec.x * @PodMaths.tec.y = @PodMaths.tec.Mult()</h5>
<h5><b>Div :</b><br>@PodMaths.tec.x / @PodMaths.tec.y = @PodMaths.tec.Div()</h5>

WebApplication2/WebApplication2/Views/Maths/PassUsingModel.cshtml
@{
    @model WebApplication2.Models.Maths

    ViewData["Title"] = "PassUsingModel";
}
<h2>PassUsingModel</h2>
<h5><b>Rand Value First :</b> @Model.x</h5>
<h5><b>Rand Value Second :</b> @Model.y</h5>
<h5><b>Add :</b><br>@Model.x + @Model.y = @Model.Add()</h5>
<h5><b>Sub :</b><br>@Model.x - @Model.y = @Model.Sub()</h5>
<h5><b>Mult :</b><br>@Model.x * @Model.y = @Model.Mult()</h5>
<h5><b>Div :</b><br>@Model.x / @Model.y = @Model.Div()</h5>

WebApplication2/WebApplication2/Views/Maths/PassUsingViewBag.cshtml
@{
    ViewBag.Title = "PassUsingViewBag";
}
<h2>@ViewBag.Title</h2>
<h5><b>Rand Value First :</b> @ViewBag.Class.x</h5>
<h5><b>Rand Value Second :</b> @ViewBag.Class.y</h5>
<h5><b>Add :</b><br>@ViewBag.Class.x + @ViewBag.Class.y = @ViewBag.Class.Add()</h5>
<h5><b>Sub :</b><br>@ViewBag.Class.x - @ViewBag.Class.y = @ViewBag.Class.Sub()</h5>
<h5><b>Mult :</b><br>@ViewBag.Class.x * @ViewBag.Class.y = @ViewBag.Class.Mult()</h5>
<h5><b>Div :</b><br>@ViewBag.Class.x / @ViewBag.Class.y = @ViewBag.Class.Div()</h5>

WebApplication2/WebApplication2/Views/Maths/PassUsingViewData.cshtml
@{
    ViewData["Title"] = "PassUsingViewData";
    var perem = ViewData["Class"] as Maths;
}
<h2> @ViewData["Title"]</h2>

<h5><b>Rand Value First :</b> @perem.x</h5>
<h5><b>Rand Value Second :</b> @perem.y</h5>
<h5><b>Add :</b><br> @perem.x + @perem.y = @perem.Add()</h5>
<h5><b>Sub :</b><br> @perem.x - @perem.y = @perem.Sub()</h5>
<h5><b>Mult :</b><br> @perem.x * @perem.y = @perem.Mult()</h5>
<h5><b>Div :</b><br> @perem.x / @perem.y = @perem.Div()</h5>

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Backend1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>                 
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <footer>
            <hr />
            <p>&copy; 2020 - Backend1</p>
        </footer>
    </div>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>