lab2/lab2/Models/Calc.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace lab2.Models
{
    public class Calc
    {
        public float x { get; set; }
        public float y { get; set; }

        public Calc()
        {
            Random ran = new Random();
            x = ran.Next(0, 10);
            y = ran.Next(0, 10);
        }

        public float Add() { return x + y; }
        public float Sub() { return x - y; }
        public float Mult() { return x * y; }

        public float Div()
        {
            if (y == 0) { return 0 ; }
            else { return x / y; }
        }
    }
}

lab2/lab2/Models/ErrorViewModel.cs
using System;

namespace lab2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab2/lab2/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using lab2.Models;

namespace lab2.Controllers
{ 
    public class CalcController : Controller
    { 
        public IActionResult Index()
    {
        return View();
    }

    public IActionResult Manual(float x, float y, char operation)
    {
        if (Request.Method == "GET")
        {
            ViewData["Title"] = "Manual";
            return View("Getall");
        }
        else
        {
            Calc cl = new Calc();
            cl.x = x;
            cl.y = y;
            ViewBag.x = cl.x;
            ViewBag.y = cl.y;
            switch (operation)
            {
                case '+': ViewBag.res = cl.Add(); ViewBag.op = '+'; break;
                case '-': ViewBag.res = cl.Sub(); ViewBag.op = '-'; break;
                case '*': ViewBag.res = cl.Mult(); ViewBag.op = '*'; break;
                case '/': ViewBag.res = cl.Div(); ViewBag.op = '/'; break;
            }

            ViewData["Title"] = "Result";
            return View("Result1");
        }

    }


    [HttpGet]
    public IActionResult ManualWithSeparateHandlers()//get
    {
        ViewData["Title"] = "ManualWithSeparateHandlers";
        return View("Getall");
    }

    [HttpPost]
    public IActionResult ManualWithSeparateHandlers(float x, float y, char operation)//get
    {
        Calc cl = new Calc();
        cl.x = x;
        cl.y = y;
        ViewBag.x = cl.x;
        ViewBag.y = cl.y;
        switch (operation)
        {
            case '+': ViewBag.res = cl.Add(); ViewBag.op = '+'; break;
            case '-': ViewBag.res = cl.Sub(); ViewBag.op = '-'; break;
            case '*': ViewBag.res = cl.Mult(); ViewBag.op = '*'; break;
            case '/': ViewBag.res = cl.Div(); ViewBag.op = '/'; break;
        }

        ViewData["Title"] = "Result";
        return View("Result1");
    }

    [HttpGet]
    public IActionResult ModelBindingInParametrs()//get
    {
        ViewData["Title"] = "ModelBindingInParametrs";
        return View("Getall");
    }

    [HttpPost]
    public IActionResult ModelBindingInParametrs([Bind("x,y")]Calc cl, char operation)//get
    {

        switch (operation)
        {
            case '+': ViewBag.res = cl.Add(); break;
            case '-': ViewBag.res = cl.Sub(); break;
            case '*': ViewBag.res = cl.Mult(); break;
            case '/': ViewBag.res = cl.Div(); break;
        }

        ViewData["Title"] = "Result";
        return View("Result2");
    }

    [HttpGet]
    public IActionResult ModelBindingInSeparateModel()//get
    {
        ViewData["Title"] = "ModelBindingInSeparateModel";
        return View("Getall");
    }

    [HttpPost]
    public IActionResult ModelBindingInSeparateModel(Calc cl, char operation)//get
    {

        switch (operation)
        {
            case '+': ViewBag.res = cl.Add(); break;
            case '-': ViewBag.res = cl.Sub(); break;
            case '*': ViewBag.res = cl.Mult(); break;
            case '/': ViewBag.res = cl.Div(); break;
        }

        ViewData["Title"] = "Result";
        return View("Result2");
    }
}

}

lab2/lab2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using lab2.Models;

namespace lab2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab2/lab2/Views/Calc/Getall.cshtml
<h2>@ViewData["Title"]</h2>
<form method="post">
    <input name="x"><br />
    <select name="operation">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
    </select><br />
    <input name="y"><br />
    <input type="submit" value="submit">
</form>

lab2/lab2/Views/Calc/Result1.cshtml
<h2>@ViewData["Title"]</h2>
<h2>@ViewBag.x @ViewBag.op @ViewBag.y = @ViewBag.res</h2>

lab2/lab2/Views/Calc/Result2.cshtml
<h2> @ViewData["Title"]</h2>
<h2> @ViewBag.res</h2>

lab2/lab2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div style=" text-align:left">
    <h2>Form parameters parsing demo</h2>
    <ul>
        <li><a asp-controller="Calc" asp-action="Manual">Manual parsing in single action</a></li>
        <li> <a asp-controller="Calc" asp-action="ManualWithSeparateHandlers">Manual parsing in separate action</a></li>
        <li> <a asp-controller="Calc" asp-action="ModelBindingInParametrs">Model binding (parameters)</a></li>
        <li> <a asp-controller="Calc" asp-action="ModelBindingInSeparateModel">Model binding (separate model)</a></li>
    </ul>
</div>

lab2/lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend2</title>

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Backend2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Backend2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>